{
	"version": 1585935297,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/q3dmodel-sheet0.png",
		"images/btnsauce-sheet0.png",
		"images/btnsauce-sheet1.png",
		"images/bg-sheet0.png",
		"images/btnupgrade-sheet0.png",
		"images/btnupgrade-sheet1.png",
		"images/btnupgrade-sheet2.png",
		"images/btnup-sheet0.png",
		"images/btndown-sheet0.png",
		"images/txtwhite.png",
		"images/txtorange.png",
		"images/txtyellow.png",
		"images/btningredientsscrollbg-sheet0.png",
		"images/revenueperpizzabg-sheet0.png",
		"images/txtgreen.png",
		"images/bgloader-sheet0.png",
		"images/loaderbar-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/hand-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/button.m4a",
		"media/button.ogg",
		"media/clicking pizza.m4a",
		"media/clicking pizza.ogg",
		"media/pizza per second.m4a",
		"media/pizza per second.ogg",
		"media/purchase.m4a",
		"media/purchase.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"1.json",
		"2.json",
		"ga_init.js",
		"three.min.js",
		"OBJLoader.js",
		"Q3D.collisionSystem.js",
		"Q3D.migrate.js",
		"Q3D.commonACE.js",
		"Q3D.qfxLoader.js",
		"WebGLDeferredRenderer.js",
		"ShaderDeferred.js",
		"CopyShader.js",
		"FXAAShader.js",
		"EffectComposer.js",
		"RenderPass.js",
		"ShaderPass.js",
		"MaskPass.js",
		"Q3D.SkinnedMesh.js"
	]
}